import { Inter, Abril_Fatface } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });
const abrilFatface = Abril_Fatface({ weight: "400", subsets: ["latin"] });
export const metadata = {
  title: "Columbus Study",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
